name: Release Automation

on:
  schedule:
    - cron: '0 12 * * 2'  # 毎週火曜の12:00に実行
  workflow_dispatch:  # 手動でのトリガーも可能

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Force push master to pre-release
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git pull origin master
          git push origin master:pre-release --force  # masterをpre-releaseに強制プッシュ

      - name: Check for changes
        id: check_changes
        run: |
          git fetch origin release
          if git diff --quiet origin/release..pre-release; then
            echo "No changes detected. Exiting."
            exit 0
          else
            echo "Changes detected."
          fi

      - name: Create Pull Request for release
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Release PR from pre-release to release'
          body: |
            This PR merges changes from `pre-release` to `release`.
          base: release
          branch: pre-release