name: Release Automation

on:
  schedule:
    - cron: '0 12 * * 2'  # 毎週火曜の12:00に実行
  workflow_dispatch:  # 手動でのトリガーも可能

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create or update pre-release branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout master
          git pull origin master
          
          # 既存の pre-release ブランチがあるか確認
          if git show-ref --verify --quiet refs/heads/pre-release; then
            git checkout pre-release
            git pull origin pre-release  # 既存のブランチを更新
          else
            git checkout -b pre-release
          fi
          
          # 変更をリモートにプッシュ
          git push origin pre-release --force  # --forceを使用して強制的にプッシュ

      - name: Create Pull Request for release
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Release PR from pre-release to release'
          body: |
            This PR merges changes from `pre-release` to `release`.
          base: release
          branch: pre-release